site_name: Документация
theme:
  name: material   # можно удалить этот блок, если тема не нужна
nav:
  - Практика: index.md
  - Лабораторная 1: index_1.md
  - Лабораторная 2: index_2.md
  - Лабораторная 3: index_3.md